name: backend
on: 
    push:
        branches:
        - master
jobs:
    copy_files_to_ec2:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
            - run: pwd
            - name: "Copying Files"
              uses: garygrossgarten/github-action-scp@release
              with:
                local: /home/runner/work/back/back
                remote: /home/ubuntu/_work/actions-runner/_work/back/back
                host: 3.6.87.167 
                username: ubuntu
                password: 1234
    Restarting_Backend:
          runs-on: self-hosted
          needs: copy_files_to_ec2
          steps:
                - run: pwd
                - run: npm install
                - run: pm2 restart back


